name: Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        run: |
          find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
